import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.CellBiologyCellSenescenceLemmaCanonicalLaneLean.CellCycleArrestPathways
import HautevilleHouse.CellBiologyCellSenescenceLemmaCanonicalLaneLean.SASPSecretoryPhenotype
import HautevilleHouse.CellBiologyCellSenescenceLemmaCanonicalLaneLean.TelomereAttritionDamage
import HautevilleHouse.CellBiologyCellSenescenceLemmaCanonicalLaneLean.SenescenceAssociatedBetaGalactosidase
import HautevilleHouse.CellBiologyCellSenescenceLemmaCanonicalLaneLean.SenescenceEvasionTumorSuppression

namespace HautevilleHouse
namespace CellBiologyCellSenescenceLemmaCanonicalLaneLean

def ConstrainedSenescenceClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_senescence_endgame (A : AdmissibleClass) :
    ConstrainedSenescenceClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end HautevilleHouse
end CellBiologyCellSenescenceLemmaCanonicalLaneLean